---
- name: "AWS - Install docker"
  hosts: localhost
  become: yes
  tasks:
    - name: Update all packages
      yum:
        name: '*'
        state: latest
        update_only: yes

    - name: Ensure a list of yum packages are installed
      yum:
        name: "{{ packages }}"
        state: latest
        update_cache: yes
      vars:
        packages:
        - python-pip
        - yum-utils
        - device-mapper-persistent-data
        - lvm2
        - amazon-linux-extras

    - name: Add extras repository
      shell: yum-config-manager --enable extras

    - name: Install docker-ce via amazon-linux-extras packages
      shell: "amazon-linux-extras install docker=18.06.1 -y"

    - name: Enable Docker CE service at startup
      service:
        name: docker
        state: started
        enabled: yes

    - name: Ensure Python pip packages are installed
      pip:
        name: "{{ packages }}"
      vars:
        packages:
        - docker-py

    - name: Log into private registry and force re-authorization
      docker_login:
        username: "{{ lookup('env', 'DOCKER_UNAME') }}"
        password: "{{ lookup('env', 'DOCKER_PASSWORD') }}"
        reauthorize: yes

    - name: pull an image
      docker_image:
        name: pasiechnyk/flask-hello
        source: pull

    - name: Cron job"
      ansible.builtin.cron:
        name: "check digest"
        minute: "2"
        job: "/home/ec2-user/docker-compare-script-main/docker-script.sh"
